import = ["/Users/kevinmaxey/.config/alacritty/themes/themes/catppuccin-mocha.toml"]

[env]
TERM = "alacritty"

[font]
size = 12

[font.bold]
style = "Regular"

[font.bold_italic]
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
key = "Comma"
mods = "Command"

[keyboard.bindings.command]
args = ["-c", "open ~/.config/alacritty/alacritty.yml"]
program = "sh"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.97

[window.padding]
x = 5
y = 5
