format = """$os $all"""

[os]
disabled = false
[os.symbols]
Macos = ""
Linux = ""

[username]
disabled = true

[hostname]
disabled = true

[directory]
style = "blue"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

[git_branch]
symbol = " "

[kubernetes]
disabled = false

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = false

# SYMBOLS

#[aws]
#symbol = " "

#[conda]
#symbol = " "

#[dart]
#symbol = " "

#[docker]
#symbol = " "

#[elixir]
#symbol = " "

#[elm]
#symbol = " "

#[golang]
#symbol = " "

#[haskell]
#symbol = " "

#[hg_branch]
#symbol = " "

[java]
symbol = " "
style = "bright-red"

#[julia]
#symbol = " "

#[nim]
#symbol = " "

[nix_shell]
symbol = " "

#[nodejs]
#symbol = " "

#[package]
#symbol = " "

#[perl]
#symbol = " "

#[php]
#symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
