format = """$os$kubernetes$directory$git_branch$git_commit$git_state$git_metrics$git_status$cmd_duration$line_break$character"""

[os]
disabled = false
[os.symbols]
Macos = " "
Linux = " "

[directory]
style = "blue"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "

[kubernetes]
disabled = false

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = false
